### PR TITLE
Attempt to build with aubio support again.

### PR DESCRIPTION
**Pull request by rncbc**

### CODE REVIEW

**Comment by hfiguiere** [comment]
build fail because waf use python that has been deprecated for a while that is now removed from 3.11

**Comment by hfiguiere** [comment]
https://docs.python.org/3/library/functions.html#open

> Changed in version 3.11: The 'U' mode has been removed.

**Comment by hfiguiere** [comment]
I pushed changes that allow the things to build.

**Comment by rncbc** [comment]
> I pushed changes that allow the things to build.

thanks @hfiguiere , without your help I wouldn't figure it out :)

**Pull request merged**
