### PR TITLE
A Spring'24 Release Candidate 2 (aka. v1.0.0-rc2)

### PR DESCRIPTION
**Pull request by rncbc**

### CODE REVIEW

**Comment by rncbc** [comment]
> Build [118583 failed](https://buildbot.flathub.org/#/builders/6/builds/118583)

@hfiguiere et al. any reason why the builders are choking on libcurl and misssing bzip2 decoder?
```
flatpak-builder: Downloading aubioDownloading https://aubio.org/pub/aubio-0.4.9.tar.bz2
  0  388k    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
Failed to download sources: module aubio: Unrecognized content encoding type. libcurl understands deflate, gzip content encodings.
program finished with exit code 1

**Comment by hfiguiere** [comment]
> > Build [118583 failed](https://buildbot.flathub.org/#/builders/6/builds/118583)
> 
> @hfiguiere et al. any reason why the builders are choking on libcurl and misssing bzip2 decoder?

I think we are hitting a bug from the curl migration. I have the same problem with SonicPi: https://github.com/flathub/net.sonic_pi.SonicPi/pull/20#issuecomment-2087786257

adding `"disable-http-decompression": true` is supposed to help but doesn't.

**Comment by hfiguiere** [comment]
It might actually work but I got distracted with crossed stream (ie it didn't build the latest).

**Comment by rncbc** [comment]
> "disable-http-decompression": true

will try this in a minute; strange that it only chokes on "aubio.json", but not on "rubberband.json" which url is also a bzip2 archive.

**Comment by hfiguiere** [comment]
It's a web server config issue.

**Comment by rncbc** [comment]
> It's a web server config issue.

ok. the `"disable-http-decompression": true` hack also fails to build; so I'll revert it asap. thanks

**Comment by hfiguiere** [comment]
it works locally. i.e. it fail without. Need to dig further.

**Comment by hfiguiere** [comment]
I filed https://github.com/flathub/flathub/issues/5213

**Pull request merged**
